import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod/v4';

export const Env = createEnv({
  server: {
    DATABASE_URL: z.string().optional(),
    DAYTONA_API_KEY: z.string().optional(),
    FIRECRAWL_API_KEY: z.string().optional(),
    FIRECRAWL_API_URL: z.string().url().optional(),
    FIRECRAWL_BROWSER_TTL: z.coerce.number().int().positive().optional(),
    FIREWORKS_API_KEY: z.string().min(1).optional(),
    FIREWORKS_BROWSER_MODEL: z.string().optional(),
    FIREWORKS_FALLBACK_MODELS: z.string().optional(),
    FIREWORKS_LIBRARIAN_MODEL: z.string().optional(),
    FIREWORKS_MODEL: z.string().optional(),
    POSTGRES_DATABASE_URL: z.string().optional(),
    POSTGRES_PRISMA_URL: z.string().optional(),
    POSTGRES_URL: z.string().optional(),
    POSTGRES_URL_NON_POOLING: z.string().optional(),
    REPL_ID: z.string().optional(),
    SESSION_SECRET: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string().optional(),
    NEXT_PUBLIC_POSTHOG_HOST: z.string().optional(),
    NEXT_PUBLIC_POSTHOG_KEY: z.string().optional(),
  },
  shared: {
    NODE_ENV: z.enum(['test', 'development', 'production']).optional(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    DAYTONA_API_KEY: process.env.DAYTONA_API_KEY,
    FIRECRAWL_API_KEY: process.env.FIRECRAWL_API_KEY,
    FIRECRAWL_API_URL: process.env.FIRECRAWL_API_URL,
    FIRECRAWL_BROWSER_TTL: process.env.FIRECRAWL_BROWSER_TTL,
    FIREWORKS_API_KEY: process.env.FIREWORKS_API_KEY,
    FIREWORKS_BROWSER_MODEL: process.env.FIREWORKS_BROWSER_MODEL,
    FIREWORKS_FALLBACK_MODELS: process.env.FIREWORKS_FALLBACK_MODELS,
    FIREWORKS_LIBRARIAN_MODEL: process.env.FIREWORKS_LIBRARIAN_MODEL,
    FIREWORKS_MODEL: process.env.FIREWORKS_MODEL,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
    NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
    NODE_ENV: process.env.NODE_ENV,
    POSTGRES_DATABASE_URL: process.env.POSTGRES_DATABASE_URL,
    POSTGRES_PRISMA_URL: process.env.POSTGRES_PRISMA_URL,
    POSTGRES_URL: process.env.POSTGRES_URL,
    POSTGRES_URL_NON_POOLING: process.env.POSTGRES_URL_NON_POOLING,
    REPL_ID: process.env.REPL_ID,
    SESSION_SECRET: process.env.SESSION_SECRET,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
