export const Env = {
  DATABASE_URL: process.env.DATABASE_URL,
  DAYTONA_API_KEY: process.env.DAYTONA_API_KEY,
  FIRECRAWL_API_KEY: process.env.FIRECRAWL_API_KEY,
  FIRECRAWL_API_URL: process.env.FIRECRAWL_API_URL,
  FIRECRAWL_BROWSER_TTL: process.env.FIRECRAWL_BROWSER_TTL
    ? Number(process.env.FIRECRAWL_BROWSER_TTL)
    : undefined,
  FIREWORKS_API_KEY: process.env.FIREWORKS_API_KEY,
  FIREWORKS_BROWSER_MODEL: process.env.FIREWORKS_BROWSER_MODEL,
  FIREWORKS_FALLBACK_MODELS: process.env.FIREWORKS_FALLBACK_MODELS,
  FIREWORKS_LIBRARIAN_MODEL: process.env.FIREWORKS_LIBRARIAN_MODEL,
  FIREWORKS_MODEL: process.env.FIREWORKS_MODEL,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
  NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
  NODE_ENV: process.env.NODE_ENV as 'development' | 'production' | 'test' | undefined,
  POSTGRES_DATABASE_URL: process.env.POSTGRES_DATABASE_URL,
  POSTGRES_PRISMA_URL: process.env.POSTGRES_PRISMA_URL,
  POSTGRES_URL: process.env.POSTGRES_URL,
  POSTGRES_URL_NON_POOLING: process.env.POSTGRES_URL_NON_POOLING,
  REPL_ID: process.env.REPL_ID,
  SESSION_SECRET: process.env.SESSION_SECRET,
};
